FROM adoptopenjdk/openjdk8:x86_64-centos-jdk8u262-b10


RUN mkdir -p /demo/api

COPY target/cocktail-demo-0.0.1-SNAPSHOT.war  /demo/api/demo.war
#COPY target/cloudmoa/opentracing-specialagent-1.7.1.jar /demo/api/opentracing-specialagent-1.7.1.jar
CMD java $JAVA_OPTIONS -jar /demo/api/demo.war